# Generated by Django 4.0.1 on 2022-02-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0003_modified_seenepisodes_for_mediastatusperuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediastatusperuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='mediastatusperuser',
            unique_together={('user', 'resource_id', 'resource_type')},
        ),
    ]
