# Generated by Django 4.0.1 on 2022-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_added_unique_together_to_media_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediastatusperuser',
            name='has_liked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
