# Generated by Django 4.0.1 on 2022-02-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_modified_has_liked_to_be_none_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediastatusperuser',
            name='has_liked',
            field=models.BooleanField(null=True),
        ),
    ]
