# Generated by Django 4.0.1 on 2022-02-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_created_games_platform_genre_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
    ]
