# Generated by Django 4.0.2 on 2022-02-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_added_show_and_episode_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='show',
        ),
        migrations.AddField(
            model_name='show',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='shows.show')),
            ],
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='shows.season'),
        ),
    ]
