# Generated by Django 4.0.1 on 2022-02-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_forced_season_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='duration',
        ),
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
