# Generated by Django 4.0.1 on 2022-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_set_name_of_show_to_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
